server:
  port: 8888
  servlet:
    context-path: /shiro
spring:
  application:
    name: shiro
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/shiro?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    database: 0
mybatis:
  type-aliases-package: com.young.shiro.sprngbootshiro.entity
  mapper-locations: classpath:mapper/*Mapper.xml

